<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Aspire.Pomelo.EntityFrameworkCore.MySql"></PackageReference>
    <PackageVersion Include="Aspire.Pomelo.EntityFrameworkCore.MySql" Version="13.4.6"></PackageVersion>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Bogus"></PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\WebApi\WebApi.csproj"></ProjectReference>
  </ItemGroup>
</Project>
